// Section 04 — Chord Progression Data
//
// 176 chord progressions extracted from ldrolez/free-midi-chords (MIT license).
// Each progression is stored as Roman numeral notation with mood tags.
// The ChordProgressionBank parses these into playable chord sequences.

export interface RawProgression {
  numerals: string[]   // e.g. ['I', 'V', 'vi', 'IV']
  moods:    string[]   // e.g. ['Hopeful', 'Romantic']
  category: 'major' | 'minor' | 'modal'
}

function parse(raw: string, category: 'major' | 'minor' | 'modal'): RawProgression {
  const [chordPart, moodPart] = raw.split('=')
  const numerals = chordPart.trim().split(/\s+/)
  const moods = moodPart ? moodPart.trim().split(/\s+/) : []
  return { numerals, moods, category }
}

// ── Major progressions (49) ──────────────────────────────────────────

const PROG_MAJ_RAW = [
  "I I IM-5 IM-5 IV IV V Vsus2 =Joyful Triumphant",
  "I I IV iii =Hopeful Nostalgic",
  "I I7 Idom7 I7 =Relaxed Playful",
  "I I7 Idom7 IV =Relaxed Nostalgic",
  "I iii IV vi =Romantic Nostalgic",
  "I iii vi Isus4 =Tender Spiritual",
  "I iii vi IV =Romantic Hopeful",
  "I IV ii V =Joyful Triumphant",
  "I IV Isus2 IV =Peaceful Hopeful",
  "I IV V IV =Joyful Triumphant",
  "I IV V =Joyful Excited",
  "I IV vi V =Joyful Hopeful",
  "I IV vii iii vi ii V I =Romantic Triumphant",
  "I V I IV =Joyful Playful",
  "I V IV vi =Romantic Hopeful",
  "I V vi ii =Hopeful Romantic",
  "I V vi iii IV I IV V =Hopeful Joyful",
  "I V vi iii IV =Hopeful Joyful",
  "I V vi IV =Hopeful Romantic",
  "I V vi V =Hopeful Romantic",
  "I vi I IV =Tender Nostalgic",
  "I vi ii IV =Tender Nostalgic",
  "I vi ii V =Nostalgic Romantic",
  "I vi IV iii =Nostalgic Romantic",
  "I vi IV V =Romantic Hopeful",
  "I7 V7 viadd9 IV7 =Playful Joyful",
  "ii IV V =Hopeful",
  "ii IV vi V =Romantic",
  "ii V I =Triumphant",
  "ii V I IV =Hopeful Triumphant",
  "ii7 Vadd9 I7 =Triumphant",
  "iii vi IV I =Romantic Nostalgic",
  "iim7 V7 iiim7 vi7 iim7 V7 =Romantic Nostalgic",
  "Isus2 I vi7 visus4 =Playful Romantic",
  "IV I ii vi =Nostalgic Peaceful",
  "IV I iii IV =Playful Joyful",
  "IV I IV6 Iadd9 =Relaxed Joyful",
  "IV I V vi =Joyful Romantic",
  "IV IV I V =Joyful Hopeful",
  "IV vi I V =Hopeful Romantic",
  "IV vi iii I =Nostalgic Playful",
  "IV vi IV vi =Nostalgic",
  "V I vi V =Hopeful Romantic",
  "V IV vi I =Hopeful Triumphant",
  "V vi IV I =Hopeful Romantic",
  "vi ii V I =Hopeful Romantic",
  "vi IV I V =Hopeful Romantic",
  "vi V IV V ii V I I =Triumphant Hopeful",
  "vi V IV V =Romantic Hopeful",
]

// ── Minor progressions (54) ──────────────────────────────────────────

const PROG_MIN_RAW = [
  "i i iv iv v7 ii5 v v7 =Dark Mysterious",
  "i ii v i =Mysterious Triumphant",
  "i III iv VI =Nostalgic Romantic",
  "i III VII VI =Nostalgic Romantic",
  "i ii v III i ii v VII =Mysterious Dramatic",
  "i iv III VI =Nostalgic Romantic",
  "i iv v iv =Mysterious Sad",
  "i iv v =Sad Lonely",
  "i iv VI v =Sad Hopeful",
  "i iv VII i =Sad Nostalgic",
  "i iv VII v i i ii V =Mysterious Surprised",
  "i v iv VII =Sad Rebellious",
  "i vdim iv VI =Dark Nostalgic",
  "i VI III VII i VI69 III7 VII =Mysterious Spiritual",
  "i VI III VII =Nostalgic Hopeful",
  "i VI iv ii =Sad Tender",
  "i VI iv III =Sad Nostalgic",
  "i VI iv v =Sad Hopeful",
  "i VI VII iv =Mysterious Nostalgic",
  "i VI VII v =Mysterious Rebellious",
  "i VI VII =Triumphant Rebellious",
  "i VII i v III VII i v i =Mysterious Surprised",
  "i VII i v =Mysterious Nostalgic",
  "i VII III VI =Rebellious Triumphant",
  "i VII v VI =Mysterious Hopeful",
  "i VII VI III iv VI VII i =Mysterious Surprised",
  "i VII VI III =Nostalgic Hopeful",
  "i VII VI iv =Sad Romantic",
  "i VII VI VII =Rebellious Triumphant",
  "i7 VI III7 VII6 i i7 III7 iv7 =Dark Nostalgic",
  "i7 VII VI7 iv7 =Nostalgic Romantic",
  "ii v i =Peaceful Hopeful",
  "ii v i iv =Peaceful Nostalgic",
  "ii VI i iv =Sad Hopeful",
  "im7 ivsus4 v7 isus4 =Mysterious Tender",
  "iv i v VI =Nostalgic Hopeful",
  "iv III VII i =Nostalgic Mysterious",
  "iv III vsus4 VI iv i III VI =Nostalgic Mysterious",
  "iv v VI VII =Mysterious Rebellious",
  "iv VI v VII =Mysterious Hopeful",
  "iv VI VII i =Triumphant",
  "v i iv VII =Dark Rebellious",
  "v iv i =Lonely",
  "v VI III i =Hopeful Nostalgic",
  "v VI v i =Sad",
  "VI i v III =Hopeful Nostalgic",
  "VI i v =Sad",
  "VI III i v =Nostalgic Dark",
  "VI iv i v =Hopeful Tender",
  "VI VI i VII =Empowered",
  "VI VII i III =Triumphant Nostalgic",
  "VI VII v III =Rebellious Nostalgic",
  "VII iv v i =Mysterious Dark",
  "VII iv VII i =Spiritual",
]

// ── Modal progressions (73) ──────────────────────────────────────────

const PROG_MODAL_RAW = [
  "bIIIM ii bIIM I =Mysterious Surprised",
  "bIIM bVIM biii bviim =Mysterious Surprised",
  "bIIM ivm biii im =Mysterious Dark",
  "bVIIM bIIM bIIIM im =Mysterious Rebellious",
  "bVIM bIIIM bVIIM IV I =Triumphant Mysterious",
  "bVIM bVIIm im bIIM =Mysterious Dark",
  "bVIM vi im bVIIM =Hopeful Mysterious",
  "bVIM7 ivmadd9 I =Spiritual Nostalgic",
  "I7 bIdom7 III7 ii7 V7 =Playful Surprised",
  "I bIIIM bVIIM I =Triumphant Rebellious",
  "I bIIIM bVIIM IV =Triumphant Mysterious",
  "I bIIIM bVIM bVIIM =Triumphant Hopeful",
  "I bIIIM IV I =Romantic",
  "I bIIM I iii =Surprised Mysterious",
  "I bIIM7 bIIIM6 bIIM7 I im bVIIM bIIM =Surprised Mysterious",
  "I bVIIM bVIM bIIM =Triumphant Rebellious",
  "I bVIIM bVIM IV IVsus4 IV =Hopeful Nostalgic",
  "I bVIIM I I bVIM V =Triumphant Hopeful",
  "I bVIIM IV V =Joyful Triumphant",
  "I bVIM I bIIM =Surprised Mysterious",
  "I bVIM IV bIIIM bVIIM =Mysterious Nostalgic",
  "I I7 I9 IV ivm =Romantic Nostalgic",
  "I I7 Idom7 IV ivm I =Relaxed Nostalgic",
  "I I7 Idom7 IV ivm I ivm6 Vdom7 =Relaxed Romantic",
  "I IIIM vi V =Joyful Hopeful",
  "I IIM iii V6 =Surprised Triumphant",
  "I IIM IV I =Joyful Triumphant",
  "I IV bIIIM bVIM =Nostalgic Mysterious",
  "I IV bVIIM IV =Joyful Rebellious",
  "I IV V bVIIM =Triumphant Rebellious",
  "I ivm bIIIM bVIIM =Mysterious Nostalgic",
  "I V bVIIM IV =Triumphant Rebellious",
  "I V ivm bVIM =Surprised Mysterious",
  "I5 iii II5 #IVm IV5 vi V5 viim =Excited Triumphant",
  "ii bIIM I bVIIM =Mysterious Rebellious",
  "ii bVIIM7 I =Hopeful Triumphant",
  "ii IVM vm bVIIM =Mysterious Nostalgic",
  "IIIM V VIsus4 VIM I IIM =Triumphant Surprised",
  "im bIIIM bVIIM IV =Romantic Nostalgic",
  "im bIIIM bVIM V =Mysterious Triumphant",
  "im bIIIM IV bVIM =Mysterious Hopeful",
  "im bIIIsus2 IV =Mysterious Hopeful",
  "im bIIM bIIIM bIIM =Mysterious Dark",
  "im bIIM biim6 ivm =Mysterious Tender",
  "im bIIM im7 bviim =Mysterious Spiritual",
  "im bIIM ivm IIIM bIIM ivm IIIM IIIM =Mysterious Nostalgic",
  "im bIIM vm im7 =Mysterious Dark",
  "im bVIIM bIIM vm =Mysterious Rebellious",
  "im bviim bVIM bIIM =Mysterious Hopeful",
  "im bVIM ivm V =Triumphant",
  "im ii vm IV =Nostalgic Hopeful",
  "im ivm9 bIIM im vm ivm7 bIIM im7 =Mysterious Tender",
  "im ivm9 bIIM im =Mysterious Nostalgic",
  "im V bVIIM IV bVIM bIIIM ivm V =Mysterious Rebellious",
  "im VIM bi V =Mysterious Triumphant",
  "im VIM IIIM bIIM =Nostalgic Surprised",
  "im vm isus4 I =Hopeful Spiritual",
  "im vm bVIM bIIM =Mysterious Hopeful",
  "im vm ivm bIIM7 =Mysterious Dark",
  "IV V ii im bIIIM IV =Hopeful Nostalgic",
  "ivm bIIIM iim7 V =Mysterious Tender",
  "ivm im bviim bVIM =Dark",
  "vdim vdim ivm bIIIM =Fearful Mysterious",
  "vi bVIM bVIIM I =Hopeful Triumphant",
  "vi IV I IIM =Hopeful Peaceful",
  "vi viim V vi #IVdim V =Nostalgic Dark",
  "VIM bVIM im bVIIM =Surprised Rebellious",
  // Cadences
  "bIIIM V7 I =Cadence",
  "bVIIM V7 I =Cadence",
  "im bVIIM IV im =Cadence",
  "ivm bIIIM bIIM I =Cadence",
  "ivm IIIM bIIM I =Cadence",
  "ivm bIIIM bVIM I =Cadence",
]

// ── Parse all progressions ───────────────────────────────────────────

export const PROGRESSIONS: RawProgression[] = [
  ...PROG_MAJ_RAW.map(r => parse(r, 'major')),
  ...PROG_MIN_RAW.map(r => parse(r, 'minor')),
  ...PROG_MODAL_RAW.map(r => parse(r, 'modal')),
]

// Total: 176 progressions
