import React from "react";
import { Link } from "wouter";
import { Scale, ArrowLeft } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen w-full bg-black/95 text-cyan-100 px-6 py-12 flex flex-col items-center overflow-y-auto astutely-scrollbar">
      {/* Background glow effects */}
      <div className="absolute top-0 left-1/4 w-96 h-96 bg-cyan-500/10 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-blue-500/10 rounded-full blur-3xl pointer-events-none" />

      <div className="w-full max-w-4xl relative z-10">
        {/* Header and Back Button */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8 border-b border-cyan-500/20 pb-6">
          <div className="flex items-center gap-3">
            <div className="p-3 rounded-xl border border-cyan-500/30 bg-cyan-500/10 shadow-[0_0_15px_rgba(6,182,212,0.25)]">
              <Scale className="h-8 w-8 text-cyan-400" />
            </div>
            <div>
              <h1 className="text-3xl font-black tracking-tight text-white uppercase">Terms of Service</h1>
              <p className="text-xs text-cyan-400/70 font-semibold tracking-wider uppercase mt-1">Last Updated: July 4, 2026</p>
            </div>
          </div>
          <Link href="/">
            <a className="inline-flex items-center gap-2 px-4 h-10 rounded-xl border border-cyan-500/30 bg-cyan-500/5 hover:bg-cyan-500/15 text-xs font-black uppercase tracking-wider text-cyan-300 transition-all cursor-pointer">
              <ArrowLeft className="w-4 h-4" />
              Back to Home
            </a>
          </Link>
        </div>

        {/* Content Card */}
        <div className="rounded-2xl border border-cyan-500/25 bg-black/70 backdrop-blur-xl p-8 md:p-12 shadow-[0_0_30px_rgba(6,182,212,0.15)] space-y-8 text-cyan-200/80 leading-relaxed text-sm">
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white uppercase tracking-wider border-l-2 border-cyan-500 pl-3">1. Agreement to Terms</h2>
            <p>
              By accessing or using the CodedSwitch workstation, AI generators, website, and related services, you agree to be bound by these Terms of Service. If you do not agree to these terms, you must not access or use the application.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white uppercase tracking-wider border-l-2 border-cyan-500 pl-3">2. Description of Services</h2>
            <p>
              CodedSwitch provides an online browser-based digital audio workstation (DAW) powered by generative music modules ("Organism AI"), audio/MIDI editors, audio visualization features, and project cloud synchronization. We reserve the right to modify, suspend, or discontinue any feature, preset, or service component at our discretion without prior notice.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white uppercase tracking-wider border-l-2 border-cyan-500 pl-3">3. Intellectual Property & Music Ownership</h2>
            <p>We believe in a creator-first approach to ownership:</p>
            <ul className="list-disc pl-5 space-y-2 text-cyan-300/80">
              <li>
                <strong className="text-white">Your Creations:</strong> You retain full ownership, copyright, and commercial exploitation rights to any audio recordings, stems, and MIDI files generated by your active workstation sessions and downloaded to your local device.
              </li>
              <li>
                <strong className="text-white">Royalty-Free Guarantee:</strong> Music created using CodedSwitch AI engines and built-in synthesizer libraries is $100\%$ royalty-free for commercial use (e.g. streaming releases, background audio, sync licensing).
              </li>
              <li>
                <strong className="text-white">Community Sharing:</strong> By opting to share your song links or publish files to the CodedSwitch Social Hub feed, you grant CodedSwitch a worldwide, non-exclusive, royalty-free license to host, stream, play, and display those specific files to other users of the platform.
              </li>
              <li>
                <strong className="text-white">Platform IP:</strong> The CodedSwitch brand, workstation software architecture, AI model scripts, UI designs, and source code are the exclusive property of CodedSwitch and are protected under copyright laws.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white uppercase tracking-wider border-l-2 border-cyan-500 pl-3">4. Acceptable Use Policies</h2>
            <p>You agree to use CodedSwitch responsibly and will not engage in the following prohibited behaviors:</p>
            <ul className="list-disc pl-5 space-y-2 text-cyan-300/80">
              <li>Uploading copyrighted third-party samples, vocal tracks, or files for which you do not own the rights.</li>
              <li>Attempting to scrape, reverse-engineer, decompile, or copy the algorithmic code of the Organism generators or synthesizer cache.</li>
              <li>Utilizing automated scripts or bots to spam the API, generate bulk accounts, or artificially inflate metrics on the Social Hub.</li>
              <li>Hosting or distributing malware, spyware, or launching security attacks against the server infrastructure.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white uppercase tracking-wider border-l-2 border-cyan-500 pl-3">5. Accounts & Payment Terms</h2>
            <p>
              Access to advanced studio capabilities may require registering an account and purchasing credits or monthly subscriptions. All payments are securely processed by Stripe. You are responsible for keeping your login credentials confidential. Purchased credits are non-refundable unless required by law.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white uppercase tracking-wider border-l-2 border-cyan-500 pl-3">6. Limitation of Liability & Disclaimers</h2>
            <p>
              CodedSwitch services are provided <span className="text-cyan-400 font-semibold">"as-is"</span> and <span className="text-cyan-400 font-semibold">"as available"</span> without warranty of any kind. While our models strive for musical originality, CodedSwitch cannot guarantee that generated melodies will not occasionally resemble existing musical works, and we assume no liability for copyright claims arising from your commercial utilization of the output.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white uppercase tracking-wider border-l-2 border-cyan-500 pl-3">7. Governing Law</h2>
            <p>
              These Terms of Service shall be governed by and construed in accordance with the laws of the jurisdiction in which CodedSwitch operates, without regard to conflict of law principles. Any dispute arising out of or relating to these terms shall be subject to the exclusive jurisdiction of the competent courts in that region.
            </p>
          </section>
        </div>

        {/* Footer */}
        <div className="mt-8 text-center text-xs text-cyan-500/50 font-bold uppercase tracking-widest">
          © 2026 CodedSwitch. All Rights Reserved.
        </div>
      </div>
    </div>
  );
}
