import type { InstrumentPerformerProfile } from './types'

export const INSTRUMENT_PERFORMERS: InstrumentPerformerProfile[] = [
  {
    id: 'guitar-nylon',
    name: 'Nylon Guitar',
    family: 'plucked',
    roles: ['lead', 'chord'],
    samplerPreset: 'acoustic_guitar_nylon',
    range: [40, 84],
    preferredOctave: 4,
    polyphony: 'poly',
    envelope: { attack: 0.006, release: 0.55 },
    volume: -7,
    defaultTechnique: 'guitar-arp-rolled',
    defaultLeadArticulation: 'grace-flick',
    defaultBassArticulation: 'none',
    modeBias: ['ice', 'glow', 'smoke'],
    tags: ['warm', 'plucked', 'intimate'],
  },
  {
    id: 'guitar-clean',
    name: 'Clean Electric Guitar',
    family: 'plucked',
    roles: ['lead', 'chord'],
    samplerPreset: 'electric_guitar_clean',
    range: [40, 88],
    preferredOctave: 4,
    polyphony: 'poly',
    envelope: { attack: 0.004, release: 0.4 },
    volume: -9,
    defaultTechnique: 'guitar-muted-stab',
    defaultLeadArticulation: 'staccato-pop',
    defaultBassArticulation: 'none',
    modeBias: ['heat', 'gravel', 'smoke'],
    tags: ['tight', 'plucked', 'rhythmic'],
  },
  {
    id: 'guitar-distorted',
    name: 'Distortion Guitar',
    family: 'plucked',
    roles: ['lead', 'chord'],
    samplerPreset: 'distortion_guitar',
    range: [40, 84],
    preferredOctave: 4,
    polyphony: 'poly',
    envelope: { attack: 0.004, release: 0.3 },
    volume: -6,
    defaultTechnique: 'guitar-muted-stab',
    defaultLeadArticulation: 'staccato-pop',
    defaultBassArticulation: 'none',
    modeBias: ['heat', 'gravel'],
    tags: ['aggressive', 'plucked'],
  },
  {
    id: 'violin',
    name: 'Violin',
    family: 'bowed',
    roles: ['lead', 'chord'],
    samplerPreset: 'violin',
    realInstrument: 'SSO_Violins1',
    range: [55, 103],
    preferredOctave: 5,
    polyphony: 'mono',
    envelope: { attack: 0.08, release: 0.55 },
    volume: -7,
    defaultTechnique: 'strings-legato',
    defaultLeadArticulation: 'legato-slur',
    defaultBassArticulation: 'none',
    modeBias: ['glow', 'smoke', 'ice'],
    tags: ['bowed', 'emotional', 'sustain'],
  },
  {
    id: 'cello',
    name: 'Cello',
    family: 'bowed',
    roles: ['lead', 'chord', 'bass'],
    samplerPreset: 'cello',
    realInstrument: 'SSO_Cello',
    range: [36, 76],
    preferredOctave: 3,
    polyphony: 'mono',
    envelope: { attack: 0.12, release: 0.9 },
    volume: -4,
    defaultTechnique: 'strings-legato',
    defaultLeadArticulation: 'legato-slur',
    defaultBassArticulation: 'bass-walking-step',
    modeBias: ['smoke', 'glow'],
    tags: ['bowed', 'warm', 'low'],
  },
  {
    id: 'bass-electric',
    name: 'Electric Bass',
    family: 'plucked',
    roles: ['bass'],
    samplerPreset: 'electric_bass_finger',
    range: [28, 55],
    preferredOctave: 2,
    polyphony: 'mono',
    envelope: { attack: 0.02, release: 0.45 },
    volume: 0,
    defaultTechnique: 'piano-block-chord',
    defaultLeadArticulation: 'none',
    defaultBassArticulation: 'bass-ghost-note',
    modeBias: ['smoke', 'glow', 'gravel'],
    tags: ['bass', 'plucked', 'warm'],
  },
  {
    id: 'bass-upright',
    name: 'Upright Bass',
    family: 'plucked',
    roles: ['bass'],
    samplerPreset: 'acoustic_bass',
    realInstrument: 'SSO_Basses',
    range: [28, 52],
    preferredOctave: 2,
    polyphony: 'mono',
    envelope: { attack: 0.05, release: 0.8 },
    volume: 1,
    defaultTechnique: 'piano-block-chord',
    defaultLeadArticulation: 'none',
    defaultBassArticulation: 'bass-walking-step',
    modeBias: ['smoke'],
    tags: ['bass', 'acoustic', 'jazz'],
  },
  {
    id: 'bass-synth',
    name: 'Synth Bass',
    family: 'synth',
    roles: ['bass'],
    samplerPreset: 'synth_bass_1',
    range: [24, 52],
    preferredOctave: 2,
    polyphony: 'mono',
    envelope: { attack: 0.004, release: 0.8 },
    volume: -5,
    defaultTechnique: 'piano-block-chord',
    defaultLeadArticulation: 'none',
    defaultBassArticulation: 'bass-slide-up',
    modeBias: ['heat', 'ice', 'gravel'],
    tags: ['bass', 'synth', '808'],
  },
  {
    id: 'flute',
    name: 'Flute',
    family: 'wind',
    roles: ['lead'],
    samplerPreset: 'flute',
    realInstrument: 'SSO_Flute',
    range: [60, 96],
    preferredOctave: 5,
    polyphony: 'mono',
    envelope: { attack: 0.035, release: 0.28 },
    volume: -6,
    defaultTechnique: 'wind-legato',
    defaultLeadArticulation: 'legato-slur',
    defaultBassArticulation: 'none',
    modeBias: ['ice', 'glow', 'smoke'],
    tags: ['wind', 'air', 'ornament'],
  },
  {
    id: 'clarinet',
    name: 'Clarinet',
    family: 'wind',
    roles: ['lead'],
    samplerPreset: 'clarinet',
    realInstrument: 'SSO_Clarinet',
    range: [50, 91],
    preferredOctave: 4,
    polyphony: 'mono',
    envelope: { attack: 0.05, release: 0.35 },
    volume: -7,
    defaultTechnique: 'wind-legato',
    defaultLeadArticulation: 'legato-slur',
    defaultBassArticulation: 'none',
    modeBias: ['smoke', 'glow'],
    tags: ['wind', 'warm'],
  },
  {
    id: 'sax',
    name: 'Alto Sax',
    family: 'wind',
    roles: ['lead'],
    samplerPreset: 'alto_sax',
    realInstrument: 'VCSL_TenorSax',
    range: [49, 85],
    preferredOctave: 4,
    polyphony: 'mono',
    envelope: { attack: 0.04, release: 0.28 },
    volume: -7,
    defaultTechnique: 'wind-run',
    defaultLeadArticulation: 'grace-flick',
    defaultBassArticulation: 'none',
    modeBias: ['smoke', 'gravel'],
    tags: ['wind', 'soulful'],
  },
  {
    id: 'trumpet',
    name: 'Trumpet',
    family: 'brass',
    roles: ['lead', 'chord'],
    samplerPreset: 'trumpet',
    realInstrument: 'SSO_Trumpet',
    range: [55, 88],
    preferredOctave: 4,
    polyphony: 'mono',
    envelope: { attack: 0.025, release: 0.25 },
    volume: -8,
    defaultTechnique: 'brass-stab',
    defaultLeadArticulation: 'staccato-pop',
    defaultBassArticulation: 'none',
    modeBias: ['heat', 'gravel', 'smoke'],
    tags: ['brass', 'stab'],
  },
  {
    id: 'piano',
    name: 'Acoustic Piano',
    family: 'keyboard',
    roles: ['lead', 'chord'],
    samplerPreset: 'acoustic_grand_piano',
    realInstrument: 'VCSL_Piano',
    range: [36, 96],
    preferredOctave: 4,
    polyphony: 'poly',
    envelope: { attack: 0.004, release: 0.9 },
    volume: -7,
    defaultTechnique: 'piano-rolled-chord',
    defaultLeadArticulation: 'none',
    defaultBassArticulation: 'none',
    modeBias: ['smoke', 'glow'],
    tags: ['keyboard', 'classic'],
  },
  {
    id: 'rhodes',
    name: 'Rhodes',
    family: 'keyboard',
    roles: ['lead', 'chord'],
    samplerPreset: 'electric_piano_1',
    realInstrument: 'SK_ElPiano01',
    range: [36, 96],
    preferredOctave: 4,
    polyphony: 'poly',
    envelope: { attack: 0.006, release: 0.7 },
    volume: -7,
    defaultTechnique: 'piano-rolled-chord',
    defaultLeadArticulation: 'legato-slur',
    defaultBassArticulation: 'none',
    modeBias: ['glow', 'smoke', 'ice'],
    tags: ['keyboard', 'warm'],
  },
  {
    id: 'strings',
    name: 'String Ensemble',
    family: 'bowed',
    roles: ['chord', 'texture'],
    samplerPreset: 'string_ensemble_1',
    realInstrument: 'VSCO2_StringSection',
    range: [36, 86],
    preferredOctave: 4,
    polyphony: 'poly',
    envelope: { attack: 0.35, release: 1.4 },
    volume: -4,
    defaultTechnique: 'strings-legato',
    defaultLeadArticulation: 'legato-slur',
    defaultBassArticulation: 'none',
    modeBias: ['glow', 'ice'],
    tags: ['bowed', 'pad'],
  },
  {
    id: 'harp',
    name: 'Harp',
    family: 'plucked',
    roles: ['lead', 'chord'],
    samplerPreset: 'orchestral_harp',
    realInstrument: 'SSO_Harp',
    range: [48, 96],
    preferredOctave: 5,
    polyphony: 'poly',
    envelope: { attack: 0.004, release: 1.2 },
    volume: -6,
    defaultTechnique: 'guitar-arp-rolled',
    defaultLeadArticulation: 'grace-flick',
    defaultBassArticulation: 'none',
    modeBias: ['ice', 'glow'],
    tags: ['plucked', 'ethereal'],
  },
  {
    id: 'sitar',
    name: 'Sitar',
    family: 'plucked',
    roles: ['lead', 'chord'],
    samplerPreset: 'sitar',
    range: [48, 91],
    preferredOctave: 5,
    polyphony: 'poly',
    envelope: { attack: 0.004, release: 0.8 },
    volume: -8,
    defaultTechnique: 'guitar-arp-rolled',
    defaultLeadArticulation: 'grace-flick',
    defaultBassArticulation: 'none',
    modeBias: ['ice', 'smoke'],
    tags: ['plucked', 'exotic'],
  },
  {
    id: 'trombone',
    name: 'Trombone',
    family: 'brass',
    roles: ['lead', 'chord', 'bass'],
    samplerPreset: 'trombone',
    realInstrument: 'SSO_Trombone',
    range: [36, 72],
    preferredOctave: 3,
    polyphony: 'mono',
    envelope: { attack: 0.04, release: 0.35 },
    volume: -6,
    defaultTechnique: 'brass-stab',
    defaultLeadArticulation: 'legato-slur',
    defaultBassArticulation: 'bass-walking-step',
    modeBias: ['gravel', 'heat', 'smoke'],
    tags: ['brass', 'warm', 'low'],
  },
  {
    id: 'french-horn',
    name: 'French Horn',
    family: 'brass',
    roles: ['lead', 'chord'],
    samplerPreset: 'french_horn',
    realInstrument: 'SSO_Horn',
    range: [40, 77],
    preferredOctave: 3,
    polyphony: 'mono',
    envelope: { attack: 0.06, release: 0.7 },
    volume: -5,
    defaultTechnique: 'brass-swell',
    defaultLeadArticulation: 'legato-slur',
    defaultBassArticulation: 'none',
    modeBias: ['glow', 'ice'],
    tags: ['brass', 'cinematic', 'warm'],
  },
  {
    id: 'oboe',
    name: 'Oboe',
    family: 'wind',
    roles: ['lead'],
    samplerPreset: 'oboe',
    realInstrument: 'SSO_Oboe',
    range: [58, 91],
    preferredOctave: 5,
    polyphony: 'mono',
    envelope: { attack: 0.03, release: 0.3 },
    volume: -7,
    defaultTechnique: 'wind-legato',
    defaultLeadArticulation: 'grace-flick',
    defaultBassArticulation: 'none',
    modeBias: ['ice', 'glow'],
    tags: ['wind', 'expressive', 'reed'],
  },
  {
    id: 'marimba',
    name: 'Marimba',
    family: 'percussion',
    roles: ['lead', 'chord'],
    samplerPreset: 'marimba',
    range: [48, 84],
    preferredOctave: 4,
    polyphony: 'poly',
    envelope: { attack: 0.003, release: 0.6 },
    volume: -6,
    defaultTechnique: 'percussion-roll',
    defaultLeadArticulation: 'staccato-pop',
    defaultBassArticulation: 'none',
    modeBias: ['ice', 'glow'],
    tags: ['percussion', 'wooden', 'bright'],
  },
  {
    id: 'vibraphone',
    name: 'Vibraphone',
    family: 'percussion',
    roles: ['lead', 'chord'],
    samplerPreset: 'vibraphone',
    range: [53, 89],
    preferredOctave: 4,
    polyphony: 'poly',
    envelope: { attack: 0.006, release: 1.2 },
    volume: -7,
    defaultTechnique: 'piano-rolled-chord',
    defaultLeadArticulation: 'legato-slur',
    defaultBassArticulation: 'none',
    modeBias: ['glow', 'ice', 'smoke'],
    tags: ['percussion', 'metallic', 'sustain'],
  },
  {
    id: 'choir',
    name: 'Choir Aahs',
    family: 'voice',
    roles: ['chord', 'texture'],
    samplerPreset: 'choir_aahs',
    range: [48, 84],
    preferredOctave: 4,
    polyphony: 'poly',
    envelope: { attack: 0.25, release: 1.5 },
    volume: -3,
    defaultTechnique: 'choir-swell',
    defaultLeadArticulation: 'legato-slur',
    defaultBassArticulation: 'none',
    modeBias: ['glow', 'ice'],
    tags: ['voice', 'pad', 'ethereal'],
  },
  {
    id: 'organ',
    name: 'Hammond Organ',
    family: 'keyboard',
    roles: ['chord', 'lead', 'bass'],
    samplerPreset: 'acoustic_grand_piano',
    range: [36, 96],
    preferredOctave: 4,
    polyphony: 'poly',
    envelope: { attack: 0.01, release: 0.3 },
    volume: -5,
    defaultTechnique: 'organ-drawbar-swell',
    defaultLeadArticulation: 'legato-slur',
    defaultBassArticulation: 'bass-walking-step',
    modeBias: ['smoke', 'glow'],
    tags: ['keyboard', 'soulful', 'gospel'],
  },
]

export const INSTRUMENT_PERFORMERS_BY_ID = new Map(
  INSTRUMENT_PERFORMERS.map(profile => [profile.id, profile])
)
